language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "8"
  - "10"
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
script:
  - yarn test
  - yarn lint
notifications:
    email: false
git:
  depth: 5